import pypc.tests.a_tests_primitives
import pypc.tests.b_tests_logic_gates
import pypc.tests.c_tests_arithmetic_
import pypc.tests.d_tests_basic_memory
import pypc.tests.e_tests_16_bit_logic
import pypc.tests.f_tests_16_bit_arithmetic